# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1239, 727)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.videoFrame = QtWidgets.QLabel(self.centralwidget)
        self.videoFrame.setGeometry(QtCore.QRect(0, 0, 600, 400))
        self.videoFrame.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.videoFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.videoFrame.setMidLineWidth(2)
        self.videoFrame.setObjectName("videoFrame")
        self.videoFrame_2 = QtWidgets.QLabel(self.centralwidget)
        self.videoFrame_2.setGeometry(QtCore.QRect(630, 0, 600, 400))
        self.videoFrame_2.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.videoFrame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.videoFrame_2.setMidLineWidth(2)
        self.videoFrame_2.setObjectName("videoFrame_2")
        self.btnCapture = QtWidgets.QPushButton(self.centralwidget)
        self.btnCapture.setGeometry(QtCore.QRect(200, 520, 171, 101))
        self.btnCapture.setObjectName("btnCapture")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(860, 530, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setObjectName("label")
        self.label_status = QtWidgets.QLabel(self.centralwidget)
        self.label_status.setGeometry(QtCore.QRect(1120, 650, 111, 31))
        self.label_status.setText("")
        self.label_status.setObjectName("label_status")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(1050, 660, 54, 12))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(473, 442, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_success = QtWidgets.QLabel(self.centralwidget)
        self.label_success.setGeometry(QtCore.QRect(580, 440, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_success.setFont(font)
        self.label_success.setText("")
        self.label_success.setObjectName("label_success")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(473, 490, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_rect = QtWidgets.QLabel(self.centralwidget)
        self.label_rect.setGeometry(QtCore.QRect(570, 480, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_rect.setFont(font)
        self.label_rect.setText("")
        self.label_rect.setObjectName("label_rect")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(470, 530, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_extend = QtWidgets.QLabel(self.centralwidget)
        self.label_extend.setGeometry(QtCore.QRect(580, 520, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_extend.setFont(font)
        self.label_extend.setText("")
        self.label_extend.setObjectName("label_extend")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(470, 560, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_circle = QtWidgets.QLabel(self.centralwidget)
        self.label_circle.setGeometry(QtCore.QRect(580, 560, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_circle.setFont(font)
        self.label_circle.setText("")
        self.label_circle.setObjectName("label_circle")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(470, 600, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_spherical = QtWidgets.QLabel(self.centralwidget)
        self.label_spherical.setGeometry(QtCore.QRect(580, 595, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_spherical.setFont(font)
        self.label_spherical.setText("")
        self.label_spherical.setObjectName("label_spherical")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(470, 640, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_leaf = QtWidgets.QLabel(self.centralwidget)
        self.label_leaf.setGeometry(QtCore.QRect(570, 640, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_leaf.setFont(font)
        self.label_leaf.setText("")
        self.label_leaf.setObjectName("label_leaf")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1239, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.videoFrame.setText(_translate("MainWindow", "Video Frame"))
        self.videoFrame_2.setText(_translate("MainWindow", "Video Frame"))
        self.btnCapture.setText(_translate("MainWindow", "拍照"))
        self.label.setText(_translate("MainWindow", "Species"))
        self.label_2.setText(_translate("MainWindow", "状态"))
        self.label_3.setText(_translate("MainWindow", "检测状态"))
        self.label_4.setText(_translate("MainWindow", "矩形度"))
        self.label_5.setText(_translate("MainWindow", "延长度"))
        self.label_6.setText(_translate("MainWindow", "似圆度"))
        self.label_7.setText(_translate("MainWindow", "球状性"))
        self.label_8.setText(_translate("MainWindow", "叶状性"))

